### ISSUE TITLE
subsequent readframe from /dev/video1 doesn't work

### ISSUE THREAD

**Issue by yakir12** [perrutquist/FFmpegPipe.jl#1]
So if I:
```julia
s1 = openvideo("/dev/video1", "r")
for i = 1:discard
    img = readframe(s1)
end
img = readframe(s1)
```
then that last `img` is real and up to date. But if I then after that do some other stuff, and then call on `
img2 = readframe(s1)` again thereafter (and the scene in front of the webcam changed) then *that* `img2` is **not** up to date -- it's not identical to the former `img`, but really similar! Weird.
Here is a small example:
```julia
using FFmpegPipe, ImageView
s1 = openvideo("/dev/video1", "r")
for i = 1:10 # just get rid of the first 10 frames
    img = readframe(s1)
end
img = readframe(s1)
imshow(img)
```
![img](https://user-images.githubusercontent.com/3281957/35160452-2222d558-fd0b-11e7-964e-c84217484fa9.png)
```julia
#... do some stuff

# ok, let's sample a new image
img2 = readframe(s1) 

# looks similar
imshow(img2)
```
![img2](https://user-images.githubusercontent.com/3281957/35160466-2d7b1e88-fd0b-11e7-9fbb-ae5e7c0b7a71.png)
```julia
# but not the same
imshow(img - img2)
```
![diff](https://user-images.githubusercontent.com/3281957/35160475-343dd364-fd0b-11e7-832c-5a5ae84c5ce6.png)

**Comment by perrutquist** [comment]
There's no two-way communication between julia and ffmpeg, other than the pipe blocking when it is not being read. So when you call readframe, you will get whatever data that was written to the pipe when space was available, and that probably happened right after your previous read.

**Comment by yakir12** [comment]
OK, I see. Fair enough.
