### ISSUE TITLE
Adapt this to jpgs

### ISSUE THREAD

**Issue by yakir12** [perrutquist/FFmpegPipe.jl#8]
https://github.com/perrutquist/FFmpegPipe.jl/blob/cc2d73acfa8ce55e3e4e53b8264c94477fa0bce3/src/FFmpegPipe.jl#L74

Hi @perrutquist ! Any chance you can push me to the right direction with adapting this function to parse JPGs instead of PNGs? The goal is to be able to read frames from this:
```
 ffmpeg -i ... -c:v mjpeg -f image2pipe -
```

**Comment by perrutquist** [comment]
The way I did it for png was to write a simple parser that did not actually decode the png, but just figure out the file length so that it could be extracted from the stream and shipped to some other library for decode. I guess you could do the same for jpg.
